fp-build should bail on error

diff --git a/scripts/fp-build b/scripts/fp-build
--- a/scripts/fp-build
+++ b/scripts/fp-build
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+# fail on the first error.
+set -e
+
 if [ -z "$FLATPAK_BUILDER" ] ; then
    if which flatpak-builder ; then
       FLATPAK_BUILDER=flatpak-builder
